<?php
/**
 * Network people grid. Profiles are intentionally presented in full here rather
 * than linking to individual person pages.
 */

$people = get_posts(
	array(
		'post_type' => 'lgsdn_person',
		'post_status' => 'publish',
		'posts_per_page' => -1,
		'orderby' => array( 'menu_order' => 'ASC', 'title' => 'ASC' ),
		'order' => 'ASC',
	)
);

if ( empty( $people ) ) {
	echo '<p ' . get_block_wrapper_attributes( array( 'class' => 'lgsdn-network__empty' ) ) . '>No network profiles have been published yet.</p>';
	return;
}

$fallback_image = get_theme_file_uri( 'assets/images/person-fallback.png' );
?>
<section <?php echo get_block_wrapper_attributes( array( 'class' => 'lgsdn-network' ) ); ?> aria-label="People in the network">
	<ul class="lgsdn-network__grid" role="list">
		<?php foreach ( $people as $person ) : ?>
			<?php
			$councils = get_the_terms( $person->ID, 'lgsdn_council' );
			$council_names = array();
			if ( is_array( $councils ) ) {
				$council_names = wp_list_pluck( $councils, 'name' );
			}
			$role = trim( (string) get_post_meta( $person->ID, 'lgsdn_role', true ) );
			$bio = has_excerpt( $person )
				? get_the_excerpt( $person )
				: wp_trim_words( wp_strip_all_tags( do_blocks( $person->post_content ) ), 34, '&hellip;' );
			$image = get_the_post_thumbnail(
				$person->ID,
				'medium',
				array(
					'class' => 'lgsdn-person-card__image',
					'alt' => '',
					'loading' => 'lazy',
					'decoding' => 'async',
					'sizes' => '(min-width: 64rem) 16rem, (min-width: 48rem) 30vw, 50vw',
				)
			);
			?>
			<li class="lgsdn-network__item">
				<article class="lgsdn-person-card" aria-labelledby="person-<?php echo esc_attr( (string) $person->ID ); ?>-name">
					<div class="lgsdn-person-card__portrait">
						<?php if ( $image ) : ?>
							<?php echo $image; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress. ?>
						<?php else : ?>
							<img class="lgsdn-person-card__image" src="<?php echo esc_url( $fallback_image ); ?>" alt="" width="768" height="768" loading="lazy" decoding="async">
						<?php endif; ?>
					</div>
					<div class="lgsdn-person-card__details">
						<?php if ( $council_names ) : ?><p class="lgsdn-person-card__council"><?php echo esc_html( implode( ', ', $council_names ) ); ?></p><?php endif; ?>
						<?php if ( $role ) : ?><p class="lgsdn-person-card__role"><?php echo esc_html( $role ); ?></p><?php endif; ?>
						<h2 class="lgsdn-person-card__name" id="person-<?php echo esc_attr( (string) $person->ID ); ?>-name"><?php echo esc_html( get_the_title( $person ) ); ?></h2>
						<?php if ( $bio ) : ?><p class="lgsdn-person-card__bio"><?php echo esc_html( $bio ); ?></p><?php endif; ?>
					</div>
				</article>
			</li>
		<?php endforeach; ?>
	</ul>
</section>
